### PR TITLE
Mn 2.x dashboard

### PR DESCRIPTION
**Pull request by Michaelndula**
Rectified the dashboards layout and stats, alignment of the invoice

### CODE REVIEW

**Comment by ningosi** [comment]
@Michaelndula hope this solves the dash board issues and graphs display?

**Comment by Michaelndula** [comment]
Yes it resolves the issue

**Comment by ningosi** [comment]
@Michaelndula when you load the invoice and check the console, there is a javascript error that is blocking your summations, please check

**Comment by Michaelndula** [comment]
Yes, I am working on it

**Comment by Michaelndula** [comment]
@ningosi I have also seen on the dashboard everything is loading zero, is it a backend issue?

**Comment by ningosi** [comment]
> @ningosi I have also seen on the dashboard everything is loading zero, is it a backend issue?

If you have no records for that time period you have selected it will be zeros always. By default the values for today need to load when the page loads, without any parameters supplied. If there are no records for today, those will be zero

**Comment by ningosi** [comment]
try selecting 26th June to today or any other date within that range. I know bigger ranges might results into error 500 because I have deleted some useful data in there that would form complete objects for the statistics

**Comment by Michaelndula** [comment]
After pulling from 2.x.x and rebuilding it, this is the error I am getting 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project financials-omod: Compilation failure
[ERROR] /home/mikey/Intellisoft-Projects/intellisoft/konza/financials/omod/src/main/java/org/openmrs/module/financials/fragment/controller/DoctorsSummariesFragmentController.java:[9,43] cannot find symbol
[ERROR]   symbol:   class ProviderPatientSimplifier
[ERROR]   location: package org.openmrs.module.financials.model

How can I solve this?

**Comment by Michaelndula** [comment]
I have some changes that I wanted to push, and I am stuck because of the error

**Comment by ningosi** [comment]
> I have some changes that I wanted to push, and I am stuck because of the error

Sorry, I mage some changes in the https://github.com/uonafya/ehrhospitalcoreopenmrs/tree/openmrs2.3.3 please clone/run the changes in your local machine to load that class

**Comment by Michaelndula** [comment]
Hi Nico, I after clonning into https://github.com/uonafya/ehrhospitalcoreopenmrs/tree/openmrs2.3.3  I tried building it but it is giving this error
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/mikey/Intellisoft-Projects/intellisoft/konza/ehrhospitalcoreopenmrs/api/src/main/java/org/openmrs/module/hospitalcore/model/PatientCategoryDetails.java:[3,19] cannot find symbol
  symbol:   class BaseChangeableOpenmrsData
  location: package org.openmrs
[ERROR] /home/mikey/Intellisoft-Projects/intellisoft/konza/ehrhospitalcoreopenmrs/api/src/main/java/org/openmrs/module/hospitalcore/model/PatientCategoryDetails.java:[4,19] cannot find symbol
  symbol:   class BaseChangeableOpenmrsMetadata
  location: package org.openmrs
[ERROR] /home/mikey/Intellisoft-Projects/intellisoft/konza/ehrhospitalcoreopenmrs/api/src/main/java/org/openmrs/module/hospitalcore/model/PatientCategoryDetails.java:[9,45] cannot find symbol
  symbol: class BaseChangeableOpenmrsMetadata
[ERROR] /home/mikey/Intellisoft-Projects/intellisoft/konza/ehrhospitalcoreopenmrs/api/src/main/java/org/openmrs/module/hospitalcore/model/PatientCategoryDetails.java:[139,3] method does not override or implement a method from a supertype
[ERROR] /home/mikey/Intellisoft-Projects/intellisoft/konza/ehrhospitalcoreopenmrs/api/src/main/java/org/openmrs/module/hospitalcore/model/PatientCategoryDetails.java:[144,3] method does not override or implement a method from a supertype
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Hospital core module 1.0.8-SNAPSHOT:
[INFO] 
[INFO] Hospital core module ............................... SUCCESS [ 15.536 s]
[INFO] Hospitalcore API ................................... FAILURE [  7.965 s]
[INFO] Hospital core module OMOD .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ----------------------------------

**Comment by Michaelndula** [comment]
never mind I forgot to switch to the openmrs2.3.3 branch :)

**Pull request merged**
